/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-10-28 07:08:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/common/template/top.jsp", Long.valueOf(1523431442000L));
    _jspx_dependants.put("/user/login.jsp", Long.valueOf(1499536822000L));
    _jspx_dependants.put("/user/modify.jsp", Long.valueOf(1572244546028L));
    _jspx_dependants.put("/user/register.jsp", Long.valueOf(1499242600000L));
    _jspx_dependants.put("/poll/polling.jsp", Long.valueOf(1499912678000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498533378000L));
    _jspx_dependants.put("/common/template/left.jsp", Long.valueOf(1499917792000L));
    _jspx_dependants.put("jar:file:/C:/SmartWeb/WebJSP/JSPLab/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafedesign/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/admin/board/boardlist.jsp", Long.valueOf(1500625792000L));
    _jspx_dependants.put("/common/template/bottom.jsp", Long.valueOf(1501490542000L));
    _jspx_dependants.put("/common/public.jsp", Long.valueOf(1499778602000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>My Cafe</title>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootswatch.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-2.1.0.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootswatch.js\"></script>\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Navigation ========================================================================================== -->\r\n");
      out.write("<div class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-responsive-collapse\">\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">My Cafe</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse navbar-responsive-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/list.jsp\">공지사항</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("<!-- 비로그인 상태 start -->\r\n");
      out.write("\t\t\t\t<li><a class=\"pill\" data-toggle=\"modal\" data-target=\"#loginModal\" data-backdrop=\"static\">로그인</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"pill\" data-toggle=\"modal\" data-target=\"#registerModal\" data-backdrop=\"static\">회원가입</a></li>\r\n");
      out.write("<!-- 비로그인 상태 end -->\r\n");
      out.write("<!-- 로그인 상태 start -->\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">로그아웃 (userId)</a></li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">마이페이지<b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/view.jsp\">개인정보</a></li>\r\n");
      out.write("                        <li><a href=\"#\">내글정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin\">관리자페이지</a></li>\r\n");
      out.write("<!-- 로그인 상태 end -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- <form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t      <div class=\"form-group\">\r\n");
      out.write("\t\t        <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <button type=\"submit\" class=\"btn btn-default\">검색</button>\r\n");
      out.write("\t\t    </form> -->\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <script>\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t$('#search').keydown(function(){\r\n");
      out.write("\t\t\t        show();\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#search').focusout(function(){\r\n");
      out.write("\t\t\t        hide();\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    function show() {\r\n");
      out.write("\t\t\t    \tvar pos = $('#search').position();\r\n");
      out.write("\t\t\t    \t//alert(pos.top + \"   \" + pos.left);\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('left', pos.left + 'px');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('top', pos.top + $('#search').height() + 15 + 'px');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('width', $('#search').width() + 25 + 'px');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('background', '#ffffff');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('opacity', '0.5');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('border-radius', '3px');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('border', '1px solid #2c3e50');\r\n");
      out.write("\t\t\t    \t$('#searchlist').css('margin', '5px');\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('display', 'block');\r\n");
      out.write("\t\t\t    \t/*\r\n");
      out.write("\t\t\t    \tvar el = $('#searchresult');\r\n");
      out.write("\t\t\t    \tif(el != null) {\r\n");
      out.write("\t\t\t    \t\tvar keyel = $('#search');\r\n");
      out.write("\t\t\t    \t\tvar kh = keyel.outerHeight();\r\n");
      out.write("\t\t\t    \t\tvar kwidth = keyel.outerWidth();\r\n");
      out.write("\t\t\t    \t\t//alert(kh + \"    \" + kwidth);\r\n");
      out.write("\t\t\t    \t\t//keyel.style.border=\"5px solid blue\";\r\n");
      out.write("\t\t\t    \t\ttempX = 0;\r\n");
      out.write("\t\t\t    \t\ttempY = 0;\r\n");
      out.write("\t\t\t    \t\tif(keyel.offsetParent()) {\r\n");
      out.write("\t\t\t    \t\t\tdo {\r\n");
      out.write("\t\t\t    \t\t\t\ttempX += keyel.offset().left;\r\n");
      out.write("\t\t\t    \t\t\t\ttempY += keyel.offset().top - (keyel.scrollTop !== 0 ? keyel.scrollTop : 0);\r\n");
      out.write("\t\t\t    \t\t\t\talert(tempX + \"   \" + tempY);\r\n");
      out.write("\t\t\t    \t\t\t} while(keyel = keyel.offsetParent());\r\n");
      out.write("\t\t\t    \t\t\ttempY += kh;\r\n");
      out.write("\t\t\t    \t\t}\r\n");
      out.write("\t\t\t    \t\talert(tempX + \"   \" + tempY);\r\n");
      out.write("\t\t\t    \t\tel.style.left = tempX + \"px\";\r\n");
      out.write("\t\t\t    \t\tel.style.top = tempY + 3 + \"px\";\r\n");
      out.write("\t\t\t    \t\tel.style.width = kwidth + \"px\";\r\n");
      out.write("\t\t\t    \t\tel.style.background = \"#ffffff\";\r\n");
      out.write("\t\t\t    \t\tel.style.display = \"block\";\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    \t*/\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    function hide() {\r\n");
      out.write("\t\t\t    \t$('#searchresult').css('display', 'none');\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t    <table>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t    \t<td>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"search\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-default\" type=\"submit\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div id=\"searchresult\" style=\"position: absolute; z-index: 1; display: none;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"searchlist\">검색결과1<br>검색결과2<br>검색결과3<br>검색결과4</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"registerModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"width: 60%;\">\r\n");
      out.write("\t    <!-- Modal content-->\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t        \t<h4 class=\"modal-title\">회원 정보 입력</h4>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"modal-body\">\r\n");
      out.write("                <form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">아이디</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <input type=\"text\" id=\"userid\" class=\"form-control\" placeholder=\"아이디\">\r\n");
      out.write("                            \t<label>사용할 수 있습니다.</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">이름</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <input type=\"text\" id=\"username\" class=\"form-control\" placeholder=\"이름\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">비밀번호</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <input type=\"password\" id=\"userpwd\" class=\"form-control\" placeholder=\"비밀번호\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">비밀번호확인</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <input type=\"password\" id=\"pwdcheck\" class=\"form-control\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">생년월일</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-10\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"생년월일 (입력 예: 2000-12-01)\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">성별</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-10\">\r\n");
      out.write("                                <div class=\"radio\">\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"optionsRadios\" id=\"optionsRadios1\" value=\"option1\" checked=\"\">\r\n");
      out.write("                                        남자\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"radio\">\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"optionsRadios\" id=\"optionsRadios2\" value=\"option2\">\r\n");
      out.write("                                        여자\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">전화번호</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3\">\r\n");
      out.write("                                <select id=\"tel1\" class=\"form-control\">\r\n");
      out.write("                                \t<option value=\"010\">010</option>\r\n");
      out.write("                                \t<option value=\"02\">02</option>\r\n");
      out.write("                                \t<option value=\"031\">031</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("                                <input type=\"text\" id=\"tel2\" class=\"form-control\" placeholder=\"1234\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-3\">\r\n");
      out.write("                                <input type=\"text\" id=\"tel3\" class=\"form-control\" placeholder=\"5678\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">우편번호</label>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"col-lg-4\">\r\n");
      out.write("                                <input type=\"text\" id=\"nzipcode\" class=\"form-control\" placeholder=\"우편번호\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label class=\"col-lg-2 control-label\">주소</label>\r\n");
      out.write("                            <div class=\"col-lg-9\">\r\n");
      out.write("                                <input type=\"text\" id=\"naddress\" class=\"form-control\" placeholder=\"주소\">\r\n");
      out.write("                                <input type=\"text\" id=\"naddress_detail\" class=\"form-control\" placeholder=\"상세주소\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                        \t<label class=\"col-lg-2 control-label\">이메일</label>\r\n");
      out.write("\r\n");
      out.write("                           \t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"eid\" class=\"form-control\" placeholder=\"이메일\">\r\n");
      out.write(" \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-5\">\r\n");
      out.write("                                <select id=\"edomain\" class=\"form-control\">\r\n");
      out.write("                                \t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                                \t<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("                                \t<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                </form>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t      \t\t<button type=\"button\" class=\"btn btn-info\">가입</button>\r\n");
      out.write("\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("     \t\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$('#loginBtn').click(function() {\r\n");
      out.write("\t\talert($('#loginModal #userid').val());\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("        \r\n");
      out.write("<div id=\"loginModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"width: 30%;\">\r\n");
      out.write("\t    <!-- Modal content-->\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t        \t<h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t    <form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t    \t<fieldset>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-lg-3 control-label\">아이디</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-lg-8\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"userid\" class=\"form-control\" placeholder=\"아이디\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-lg-3 control-label\">비밀번호</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-lg-8\">\r\n");
      out.write("\t                        <input type=\"password\" id=\"userpwd\" class=\"form-control\" placeholder=\"비밀번호\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t      \t\t<button type=\"button\" id=\"loginBtn\" class=\"btn btn-info\">로그인</button>\r\n");
      out.write("\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Container ======================================================================================= -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- left ======================================================================================= -->\r\n");
      out.write("    \t<div class=\"col-sm-3\">\r\n");
      out.write("    \t\t<div style=\"height: 10px;\"></div>\r\n");
      out.write("    \t\t\r\n");
      out.write("            <!-- user info ======================================================================================= -->\r\n");
      out.write("    \t\t<div>\r\n");
      out.write("    \t\t\t<div style=\"height: 180px; text-align: center;\">\r\n");
      out.write("    \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/main/main_0.jpg\" class=\"img-rounded\" alt=\"Cinque Terre\" width=\"180\" align=\"middle\">\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<div style=\"height: 10px;\"></div>\r\n");
      out.write("    \t\t\r\n");
      out.write("            <!-- board menu ======================================================================================= -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("            \t//게시판 펼치기\r\n");
      out.write("            \t$('#categoryOpen').click(function() {\r\n");
      out.write("            \t\t$(this).parent().siblings('li').children('div.tab-content').slideDown(100);\r\n");
      out.write("            \t\t$(this).css('display', 'none');\r\n");
      out.write("            \t\t$('#categoryClose').css('display', '');\r\n");
      out.write("            \t});\r\n");
      out.write("            \t//게시판 접기\r\n");
      out.write("            \t$('#categoryClose').click(function() {\r\n");
      out.write("            \t\t$(this).parent().siblings('li').children('div.tab-content').slideUp(100);\r\n");
      out.write("            \t\t$(this).css('display', 'none');\r\n");
      out.write("            \t\t$('#categoryOpen').css('display', '');\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$('#board_menu a.category_name').click(function() {\r\n");
      out.write("            \t\t//$(this).siblings('div.tab-content').css({'color' : 'red', 'border' : '2px solid pink'}).parent().siblings('li').children('div.tab-content').css({'color' : 'red', 'border' : '2px solid blue'});\r\n");
      out.write("            \t\t$(this).siblings('div.tab-content').slideDown(100).parent().siblings('li').children('div.tab-content').slideUp(100);\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$('.movelist').click(function() {\r\n");
      out.write("            \t\talert($(this).attr('data-bcode') + \"번 게시판으로 이동!!!!\");\r\n");
      out.write("            \t\t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.jsp');\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("            </script>\r\n");
      out.write("            <div>\r\n");
      out.write("            \t<ul id=\"board_menu\" class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("            \t\t<li>\r\n");
      out.write("\t\t\t\t    \t<a id=\"categoryOpen\" data-toggle=\"pill\" style=\"background: #bdc1d5; display: none;\">모든게시판펼치기</a>\r\n");
      out.write("\t\t\t\t    \t<a id=\"categoryClose\" data-toggle=\"pill\" style=\"background: #bdc1d5;\">모든게시판접기</a>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t    \t<a class=\"category_name\" data-toggle=\"pill\" href=\"#home\" style=\"background: #bcbcbc;\">갤럭시S8</a>\r\n");
      out.write("\t\t\t\t    \t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t    \t\t<div id=\"menu1\">\r\n");
      out.write("\t\t\t\t    \t\t\t<ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"1\">[갤럭시S8] 공지</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"2\">[갤럭시S8] 궁금해요</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"3\">[갤럭시S8] 공유해요</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t    \t<a class=\"category_name\" data-toggle=\"pill\" href=\"#menu1\" style=\"background: #bcbcbc;\">갤럭시노트8</a>\r\n");
      out.write("\t\t\t\t    \t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t    \t\t<div id=\"menu2\">\r\n");
      out.write("\t\t\t\t    \t\t\t<ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"4\">[갤럭시노트8] 사용법</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"5\">[갤럭시노트8] Q&amp;A</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"6\">[갤럭시노트8] 자랑하기</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t    \t<a class=\"category_name\" data-toggle=\"pill\" href=\"#menu2\" style=\"background: #bcbcbc;\">아이폰8Plus</a>\r\n");
      out.write("\t\t\t\t    \t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t    \t\t<div id=\"menu3\">\r\n");
      out.write("\t\t\t\t    \t\t\t<ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"7\">[아이폰8Plus] 숙지하세요</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"8\">[아이폰8Plus] 묻고답하기</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"9\">[아이폰8Plus] 스크린샷</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t    \t<a class=\"category_name\" data-toggle=\"pill\" href=\"#menu3\" style=\"background: #bcbcbc;\">G7</a>\r\n");
      out.write("\t\t\t\t    \t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t    \t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t    \t\t<div id=\"menu4\">\r\n");
      out.write("\t\t\t\t    \t\t\t<ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"10\">[G7] 공지사항</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"11\">[G7] 사용설명</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<li style=\"margin-left: 5%\"><a class=\"movelist\" data-toggle=\"collapse\" data-bcode=\"12\">[G7] 자료</a></li>\r\n");
      out.write("\t\t\t\t    \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t  \t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div style=\"height: 10px;\"></div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- board menu ======================================================================================= -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\" style=\"border: 2px solid #bcbcbc; border-radius: 10px;\">\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t                <h5 style=\"color: #000066;\"><strong>[ 투표해요 !!! ]</strong></h5>\r\n");
      out.write("\t            </div><br>\r\n");
      out.write("\t\t\t    <form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t    \t<fieldset>\r\n");
      out.write("\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t                    <div class=\"col-sm-12\">\r\n");
      out.write("\t                    \t<label id=\"question\">가장 좋아하는 과목은?</label>\r\n");
      out.write("\t                        <div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t<label><input type=\"radio\" name=\"answer\" id=\"answer\" value=\"\">JAVA</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t<label><input type=\"radio\" name=\"answer\" id=\"answer\">JSP</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t<label><input type=\"radio\" name=\"answer\" id=\"answer\">Spring</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t<label><input type=\"radio\" name=\"answer\" id=\"answer\">Android</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"form-group pull-right\">\r\n");
      out.write("\t\t                <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t      \t\t<button type=\"button\" id=\"pollBtn\" class=\"btn btn-xs btn-info\">투표하기</button>\r\n");
      out.write("\t\t\t\t        \t<button type=\"button\" id=\"resultBtn\" class=\"btn btn-xs btn-default\">결과보기</button>\r\n");
      out.write("\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div class=\"pull-right\">\r\n");
      out.write("                   \t\t<label id=\"period\">투표기간 : 2017.07.01 ~ 2017.07.30</label>\r\n");
      out.write("                   \t</div>\r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Center ======================================================================================= -->\r\n");
      out.write("        <div class=\"col-sm-9\">\r\n");
      out.write("        \t<div class=\"page-header\">\r\n");
      out.write("                <h2 id=\"container\">회원 정보</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table table-bordered\">\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                        <col width=\"120\">\r\n");
      out.write("                        <col width=\"*\">\r\n");
      out.write("                        <col width=\"120\">\r\n");
      out.write("                        <col width=\"*\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"text-center\">ID(이메일)</th>\r\n");
      out.write("                        <td class=\"text-left\">kglim(i7027@naver.com)</td>\r\n");
      out.write("                        <th class=\"text-center\">회원명</th>\r\n");
      out.write("                        <td class=\"text-left\">임경균</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    \t<th class=\"text-center\">전화번호</th>\r\n");
      out.write("                        <td class=\"text-left\">010-0000-0000</td>\r\n");
      out.write("                        <th class=\"text-center\">가입일</th>\r\n");
      out.write("                        <td class=\"text-left\">2019.07.03 15:25:56</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"text-center\">주소</th>\r\n");
      out.write("                        <td class=\"text-left\" colspan=\"3\">서울시 강남구 역삼동</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("            \t$('#modiBtn').click(function() {\r\n");
      out.write("            \t\t$('#modifyModal').on('show.bs.modal', function(event) {\r\n");
      out.write("                \t\tvar modal = $(this)\r\n");
      out.write("              \t\t  \tmodal.find('#userpwd').val('1234');\r\n");
      out.write("                \t\tmodal.find('#eid').val('java2');\r\n");
      out.write("                \t\tmodal.find('#edomain').val('nate.com');\r\n");
      out.write("                \t\tmodal.find('#tel1').val('031');\r\n");
      out.write("                \t\tmodal.find('#tel2').val('1234');\r\n");
      out.write("              \t\t  \tmodal.find('#tel3').val('5678');\r\n");
      out.write("              \t\t \tmodal.find('#nzipcode').val('58965');\r\n");
      out.write("              \t\t  \tmodal.find('#naddress').val('경기도 성남시 중원구');\r\n");
      out.write("              \t\t  \tmodal.find('#naddress_detail').val('469');\r\n");
      out.write("              \t\t});          \t\r\n");
      out.write("              \t\t$('#modifyModal').modal();\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("            </script>\r\n");
      out.write("            <div class=\"pull-right\">\r\n");
      out.write("            \t<button type=\"button\" id=\"modiBtn\" class=\"btn btn-success\" data-backdrop=\"static\">수정</button>\r\n");
      out.write("            \t<!-- button type=\"button\" class=\"btn btn-success\" data-toggle=\"modal\" data-target=\"#modifyModal\" data-backdrop=\"static\">수정</button -->\r\n");
      out.write("                <!-- a href=\"./modify.html\" class=\"btn btn-success btn-default\">수정</a-->\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-large btn-default\">탈퇴</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 회원정보 수정 Modal -->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#modifyBtn').click(function() {\r\n");
      out.write("\t\t\t\talert($('#modifyModal #eid').val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("        </script>\r\n");
      out.write("\t\t<div id=\"modifyModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t    <!-- Modal content-->\r\n");
      out.write("\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t        \t<h4 class=\"modal-title\">회원 정보 수정</h4>\r\n");
      out.write("\t\t\t      \t</div>\r\n");
      out.write("\t\t\t      \t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t        \t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t        \t<form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t                <table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t                    <colgroup>\r\n");
      out.write("\t\t\t                        <col width=\"120\">\r\n");
      out.write("\t\t\t                        <col width=\"*\">\r\n");
      out.write("\t\t\t                        <col width=\"120\">\r\n");
      out.write("\t\t\t                        <col width=\"*\">\r\n");
      out.write("\t\t\t                    </colgroup>\r\n");
      out.write("\t\t\t                    <tbody>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                        <th class=\"text-center\">ID</th>\r\n");
      out.write("\t\t\t                        <td id=\"userid\" class=\"text-left\">java2</td>\r\n");
      out.write("\t\t\t                        <th class=\"text-center\">회원명</th>\r\n");
      out.write("\t\t\t                        <td id=\"username\" class=\"text-left\">임경균</td>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                    \t<th class=\"text-center\">비밀번호</th>\r\n");
      out.write("\t\t\t                        <td class=\"text-left\" colspan=\"3\">\r\n");
      out.write("\t\t\t                            <div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t                                <input type=\"password\" id=\"userpwd\" class=\"form-control\" placeholder=\"비밀번호\">\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                        </td>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                        <th class=\"text-center\">이메일</th>\r\n");
      out.write("\t\t\t                        <td class=\"text-left\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t                        <div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"eid\" class=\"form-control\" placeholder=\"이메일\">\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-7\">\r\n");
      out.write("\t\t\t                                <select id=\"edomain\" class=\"form-control\">\r\n");
      out.write("\t\t\t                                \t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t                                \t<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t                                \t<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("\t\t\t                                </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t                        </td>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                    \t<th class=\"text-center\">전화번호</th>\r\n");
      out.write("\t\t\t                        <td class=\"text-left\" colspan=\"3\">\r\n");
      out.write("\t\t\t                        \t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t                                <select id=\"tel1\" class=\"form-control\">\r\n");
      out.write("\t\t\t                                \t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t                                \t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t                                \t<option value=\"031\">031</option>\r\n");
      out.write("\t\t\t                                </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t                                <input type=\"text\" id=\"tel2\" class=\"form-control\" placeholder=\"1234\">\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            <div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t                                <input type=\"text\" id=\"tel3\" class=\"form-control\" placeholder=\"5678\">\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                        </td>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                        <th class=\"text-center\">주소</th>\r\n");
      out.write("\t\t\t                        <td class=\"text-left\" colspan=\"3\">\r\n");
      out.write("\t\t\t                        \t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t                                <input type=\"text\" id=\"nzipcode\" class=\"form-control\" placeholder=\"우편번호\">\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                       \t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t                                <input type=\"text\" id=\"naddress\" class=\"form-control\" placeholder=\"주소\">\r\n");
      out.write("\t\t\t                                <input type=\"text\" id=\"naddress_detail\" class=\"form-control\" placeholder=\"상세주소\">\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                        </td>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                    </tbody>\r\n");
      out.write("\t\t\t                </table>\r\n");
      out.write("\t\t\t            </form>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t      \t</div>\r\n");
      out.write("\t\t\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t      \t\t<button type=\"button\" id=\"modifyBtn\" class=\"btn btn-info\">수정</button>\r\n");
      out.write("\t\t\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t      \t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer ========================================================================================== -->\r\n");
      out.write("     <footer>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li class=\"pull-right\"><a href=\"#top\">위로 이동</a></li>                    \r\n");
      out.write("\t                <li><a href=\"#\">MyCafe 홈</a></li>                    \r\n");
      out.write("                    <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                    <li><a href=\"#\">도움말</a></li>\r\n");
      out.write("                    <li><a href=\"#\">회원탈퇴</a></li>                  \r\n");
      out.write("                </ul>\r\n");
      out.write("                <p>© MyCafe 2020.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /common/public.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /common/public.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/common/public.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
