/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-10-28 07:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hl.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Travelpackage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--Travel Package-->\r\n");
      out.write("  <div class=\"row text-center\" id=\"package\">\r\n");
      out.write("        <h1>2019 베스트 여행지</h1>\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("            <div class=\"thumbnail\">\r\n");
      out.write("                <img src=\"./images/iceland.jpg\" alt=\"iceland\" width=\"300px\" height=\"auto\">\r\n");
      out.write("                <p><strong>아이슬란드</strong></p>\r\n");
      out.write("                <button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal_1\">감상</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./images/kota.jpg\" alt=\"kota\" width=\"300px\" height=\"auto\">\r\n");
      out.write("                    <p><strong>코타키나발루</strong></p>\r\n");
      out.write("                    <button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal_2\">감상</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./images/jeju.jpg\" alt=\"jeju\" width=\"300px\" height=\"auto\">\r\n");
      out.write("                    <p><strong>제주도 왕따나무</strong></p>\r\n");
      out.write("                    <button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal_3\">감상</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Book Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal_1\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <!-- Modal content-->\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("            <h3><span class=\"modal-title\"></span>코타키나발루</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <p>온 세상을 붉게 물들이는 세계 3대 석양, 다양한 해양스포츠를 즐길 수 있는 툰구압둘라만 해양국립공원, 말레이시아 전통생활을 볼 수 있는 민속마을까지 코타키나발루 구석구석을 둘러볼 수 있는 상품으로 전일정 관광 및 식사가 포함되어 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-danger btn-default pull-left\" data-dismiss=\"modal\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-remove\"></span> close\r\n");
      out.write("            </button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default pull-right\" data-dismiss=\"modal\"\r\n");
      out.write("            onclick=\"open_page('https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=147897375')\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-search\"></span> 책정보\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal_2\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <!-- Modal content-->\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                <h3><span class=\"modal-title\"></span>아이슬란드</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <p>대자연의 신비를 간직한 아이슬란드를 일주하는 상품입니다.<br>#아이슬란드 #오로라 #오로라헌팅 #싱벨리어 #레이캬비크 #빙하 #빙산 #간헐천 #골든서클 #싱벨리어 #굴포스 #폭포 #얼음 #블루라군 #온천 #만년설 #유럽여행 #힐링여행 #출사여행 #버킷리스트 #TV속여행지</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger btn-default pull-left\" data-dismiss=\"modal\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-remove\"></span> close\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default pull-right\" data-dismiss=\"modal\"\r\n");
      out.write("                onclick=\"open_page('https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=192372285')\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-search\"></span> 책정보\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal_3\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <!-- Modal content-->\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                <h3><span class=\"modal-title\"></span>제주도</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <p>아름다운 제주에서 현대인의 쓸쓸함에 대해 사색하는 시간</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger btn-default pull-left\" data-dismiss=\"modal\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-remove\"></span> close\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default pull-right\" data-dismiss=\"modal\"\r\n");
      out.write("                onclick=\"open_page('https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=171698547')\">\r\n");
      out.write("                <span class=\"glyphicon glyphicon-search\"></span> 책정보\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
