/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-10-28 06:36:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class makeboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/admin/board/boardmodify.jsp", Long.valueOf(1501662370000L));
    _jspx_dependants.put("/common/template/admintop.jsp", Long.valueOf(1501661330000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498533378000L));
    _jspx_dependants.put("jar:file:/C:/SmartWeb/WebJSP/JSPLab/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafedesign/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/common/public.jsp", Long.valueOf(1499778602000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>My Cafe</title>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootswatch.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-2.1.0.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootswatch.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js\"></script>\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Navigation ========================================================================================== -->\r\n");
      out.write("<div class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-responsive-collapse\">\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">My Cafe</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse navbar-responsive-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li id=\"amember\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">회원</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/list.jsp\">회원 리스트</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"anotice\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">공지사항</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/notice/list.jsp\">공지사항 리스트</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"aboard\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">게시판</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board/makecategory.jsp\">카테고리생성</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board/makeboard.jsp\">게시판생성</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"apoll\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">POLL</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/poll/list.jsp\">이전 poll 리스트</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"astats\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">통계</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats/list.jsp\">회원 거주지 분포</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats/list.jsp\">게시판별 등록글</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats/list.jsp\">등록글별 댓글</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">로그아웃 (userId)</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Container ======================================================================================= -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Center ======================================================================================= -->\r\n");
      out.write("        <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t    <h2 id=\"container\">게시판생성 및 변경</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("           \t\r\n");
      out.write("           \t<script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("            \tvar selectcategory = '';\r\n");
      out.write("            \tvar selecttype = '';\r\n");
      out.write("            \t$(document).on('change', '#ccode', function() {\r\n");
      out.write("            \t\tselectcategory = $('#ccode option:selected').text();\r\n");
      out.write("            \t\t$('#boardnames').text(selectcategory);\r\n");
      out.write("            \t\t$('#mcategory').text(selectcategory);\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$(document).on('change', '#btype', function() {\r\n");
      out.write("            \t\tselecttype = $('#btype option:selected').text();\r\n");
      out.write("            \t\t$('#mtype').text(selecttype);\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$(document).on('click', '#bmodifyBtn', function() {\r\n");
      out.write("            \t\tvar bcode = $(this).parents('li').attr('data-bcode');\r\n");
      out.write("            \t\tvar oldname = $(this).parents('li').children('.bname').text();\r\n");
      out.write("            \t\t$('#boardModifyModal').on('show.bs.modal', function(event) {\r\n");
      out.write("                \t\tvar modal = $(this);\r\n");
      out.write("                \t\tmodal.find('#oldbname').text(oldname);\r\n");
      out.write("                \t\tmodal.find('#newbname').val('');\r\n");
      out.write("                \t\tmodal.find('#bcode').val(bcode);\r\n");
      out.write("              \t\t});          \t\r\n");
      out.write("              \t\t$('#boardModifyModal').modal();\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$(document).on('click', '#bdeleteBtn', function() {\r\n");
      out.write("            \t\talert($(this).parents('li').attr('data-bcode'));\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t$(document).on('click', '#createBtn', function() {\r\n");
      out.write("            \t\tif($('#ccode option:selected').length != 1) {\r\n");
      out.write("            \t\t\talert('한개의 카테고리를 선택하세요');\r\n");
      out.write("            \t\t\treturn;\r\n");
      out.write("            \t\t} else if($('#btype option:selected').length != 1) {\r\n");
      out.write("            \t\t\talert('한개의 게시판형식을 선택하세요');\r\n");
      out.write("            \t\t\treturn;\r\n");
      out.write("            \t\t} else if($.trim($('#bname').val()) == '') {\r\n");
      out.write("            \t\t\talert('게시판 이름 입력하세요');\r\n");
      out.write("            \t\t\treturn;\r\n");
      out.write("            \t\t} else {\r\n");
      out.write("            \t\t\talert(selectcategory + '카테고리에 ' + selecttype + '형식의 ' + $('#bname').val() + '이름으로 게시판생성!!!');\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write(" \t\t\t\t<form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t    \t<fieldset>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-12 control-label\">카테고리 선택</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-12\">\r\n");
      out.write("\t                        <select multiple class=\"form-control\" id=\"ccode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\" data-bn=\"갤럭시S9\">갤럭시S9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\" data-bn=\"갤럭시Note8\">갤럭시Note8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\" data-bn=\"아이폰8SPlus\">아이폰8SPlus</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\" data-bn=\"G7\">G7</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-12 control-label\">게시판형식 선택</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-12\">\r\n");
      out.write("\t                        <select multiple class=\"form-control\" id=\"btype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">공지사항</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">방명록</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">한줄메모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">일반형게시판</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"5\">답변형게시판</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"6\">앨범형게시판</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"7\">자료실</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-12 control-label\">현재  <span id=\"boardnames\"></span> 게시판</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-12\" style=\"margin-left: 15px; padding: 10px; border: 1px solid #bcbcbc; border-radius: 5px;\">\r\n");
      out.write("\t                        <ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t                        \t<li data-bcode=\"10\">\r\n");
      out.write("\t                        \t\t<div class=\"bname col-sm-10\">공지해요</div>\r\n");
      out.write("\t                        \t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t\t\t<button type=\"button\" id=\"bmodifyBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">이름변경</button>\r\n");
      out.write("\t\t\t\t            \t\t\t<button type=\"button\" id=\"bdeleteBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">삭제</button>\r\n");
      out.write("\t                        \t\t</div>\r\n");
      out.write("\t                        \t</li>\r\n");
      out.write("\t                        \t<li data-bcode=\"9\">\r\n");
      out.write("\t                        \t\t<div class=\"bname col-sm-10\">출석체크해요</div>\r\n");
      out.write("\t                        \t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t\t\t<button type=\"button\" id=\"bmodifyBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">이름변경</button>\r\n");
      out.write("\t\t\t\t            \t\t\t<button type=\"button\" id=\"bdeleteBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">삭제</button>\r\n");
      out.write("\t                        \t\t</div>\r\n");
      out.write("\t                        \t</li>\r\n");
      out.write("\t                        \t<li data-bcode=\"8\">\r\n");
      out.write("\t                        \t\t<div class=\"bname col-sm-10\">일상생활이야기</div>\r\n");
      out.write("\t                        \t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t\t\t<button type=\"button\" id=\"bmodifyBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">이름변경</button>\r\n");
      out.write("\t\t\t\t            \t\t\t<button type=\"button\" id=\"bdeleteBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">삭제</button>\r\n");
      out.write("\t                        \t\t</div>\r\n");
      out.write("\t                        \t</li>\r\n");
      out.write("\t                        \t<li data-bcode=\"7\">\r\n");
      out.write("\t                        \t\t<div class=\"bname col-sm-10\">궁금해요</div>\r\n");
      out.write("\t                        \t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t\t\t<button type=\"button\" id=\"bmodifyBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">이름변경</button>\r\n");
      out.write("\t\t\t\t            \t\t\t<button type=\"button\" id=\"bdeleteBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">삭제</button>\r\n");
      out.write("\t                        \t\t</div>\r\n");
      out.write("\t                        \t</li>\r\n");
      out.write("\t                        \t<li data-bcode=\"6\">\r\n");
      out.write("\t                        \t\t<div class=\"bname col-sm-10\">자랑할래요</div>\r\n");
      out.write("\t                        \t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t\t\t<button type=\"button\" id=\"bmodifyBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">이름변경</button>\r\n");
      out.write("\t\t\t\t            \t\t\t<button type=\"button\" id=\"bdeleteBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">삭제</button>\r\n");
      out.write("\t                        \t\t</div>\r\n");
      out.write("\t                        \t</li>\r\n");
      out.write("\t                        \t<li data-bcode=\"5\">\r\n");
      out.write("\t                        \t\t<div class=\"bname col-sm-10\">공유해요</div>\r\n");
      out.write("\t                        \t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t\t\t<button type=\"button\" id=\"bmodifyBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">이름변경</button>\r\n");
      out.write("\t\t\t\t            \t\t\t<button type=\"button\" id=\"bdeleteBtn\" class=\"btn btn-xs btn-link\" data-backdrop=\"static\">삭제</button>\r\n");
      out.write("\t                        \t\t</div>\r\n");
      out.write("\t                        \t</li>\r\n");
      out.write("\t                        </ul>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"form-group col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-12 control-label\">생성할 게시판이름</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-12\" style=\"margin-left: 15px; padding: 10px; border: 1px solid #bcbcbc; border-radius: 5px;\">\r\n");
      out.write("\t                        <div class=\"col-sm-10\">\r\n");
      out.write("\t                        \t<label class=\"col-sm-12\"><span id=\"mcategory\"></span> &gt;&gt; <span id=\"mtype\"></span></label>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"col-sm-10\">\r\n");
      out.write("\t                        \t<input type=\"text\" id=\"bname\" class=\"form-control\" placeholder=\"게시판이름\">\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"col-sm-2\">\r\n");
      out.write("\t                        \t<button type=\"button\" id=\"createBtn\" class=\"btn btn-info\">게시판생성</button>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write(" \t\t\t</div>\r\n");
      out.write("       \t</div>\r\n");
      out.write("<!-- 게시판이름변경 Modal -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"boardModifyModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"width: 50%;\">\r\n");
      out.write("\t    <!-- Modal content-->\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t        \t<h4 class=\"modal-title\">게시판이름변경</h4>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t    <form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t    \t<input type=\"hidden\" name=\"bcode\" id=\"bcode\">\r\n");
      out.write("\t\t\t    \t<fieldset>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-lg-3 control-label\">기존게시판이름</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <label id=\"oldbname\" class=\"col-lg-8 control-label\"></label>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-lg-3 control-label\">변경할게시판이름</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-lg-8\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"newbname\" class=\"form-control\" placeholder=\"게시판새이름\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("            \t$('#bnameModifyBtn').click(function() {\r\n");
      out.write("            \t\talert($('#bcode').val() + '번 게시판이름을 ' + $('#newbname').val() + '로 변경합니다.');\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("            </script>\r\n");
      out.write("\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t      \t\t<button type=\"button\" id=\"bnameModifyBtn\" class=\"btn btn-info\">게시판이름변경</button>\r\n");
      out.write("\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /common/public.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /common/public.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/common/public.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
