/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-10-28 06:36:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.poll;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/admin/poll/view.jsp", Long.valueOf(1500700026000L));
    _jspx_dependants.put("/admin/poll/modify.jsp", Long.valueOf(1500567996000L));
    _jspx_dependants.put("/admin/poll/write.jsp", Long.valueOf(1500612162000L));
    _jspx_dependants.put("/common/template/admintop.jsp", Long.valueOf(1501661330000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498533378000L));
    _jspx_dependants.put("jar:file:/C:/SmartWeb/WebJSP/JSPLab/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafedesign/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/common/public.jsp", Long.valueOf(1499778602000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>My Cafe</title>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootswatch.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-2.1.0.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootswatch.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js\"></script>\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Navigation ========================================================================================== -->\r\n");
      out.write("<div class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-responsive-collapse\">\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">My Cafe</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse navbar-responsive-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li id=\"amember\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">회원</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/list.jsp\">회원 리스트</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"anotice\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">공지사항</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/notice/list.jsp\">공지사항 리스트</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"aboard\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">게시판</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board/makecategory.jsp\">카테고리생성</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board/makeboard.jsp\">게시판생성</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"apoll\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">POLL</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/poll/list.jsp\">이전 poll 리스트</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"astats\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">통계</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats/list.jsp\">회원 거주지 분포</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats/list.jsp\">게시판별 등록글</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/stats/list.jsp\">등록글별 댓글</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">로그아웃 (userId)</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Container ======================================================================================= -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Center ======================================================================================= -->\r\n");
      out.write("        <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t    <h2 id=\"container\">온라인투표</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t<a class=\"pill\" data-toggle=\"modal\" data-target=\"#pollWriteModal\" data-backdrop=\"static\">\r\n");
      out.write("           \t\t<button type=\"button\" id=\"newBtn\" class=\"btn btn-sm btn-default\" data-backdrop=\"static\">투표생성</button>\r\n");
      out.write("           \t\t</a>\r\n");
      out.write("           \t</div>\r\n");
      out.write("           \t\r\n");
      out.write("           \t<script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("            \t//네비바 체크\r\n");
      out.write("            \t$('#apoll').addClass('active');\r\n");
      out.write("            \t\r\n");
      out.write("            \t//결과보기\r\n");
      out.write("            \t$('.btn.btn-xs.btn-primary').click(function() {\r\n");
      out.write("            \t\tvar seq = $(this).parents('td').siblings().eq(0).text();\r\n");
      out.write("            \t\talert(seq + \"번 투표 결과보기 이동!!!\");\r\n");
      out.write("            \t\t$('#pollResultModal').on('show.bs.modal', function(event) {\r\n");
      out.write("            \t\t\tvar modal = $(this)\r\n");
      out.write("              \t\t  \tmodal.find('#charttype1').val('pie');\r\n");
      out.write("              \t\t  \tmodal.find('#charttype2').val('doughnut');\r\n");
      out.write("              \t\t});          \t\r\n");
      out.write("              \t\t$('#pollResultModal').modal();\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t//투표수정\r\n");
      out.write("            \t$('.btn.btn-xs.btn-info').click(function() {\r\n");
      out.write("            \t\tvar seq = $(this).parents('td').siblings().eq(0).text();\r\n");
      out.write("            \t\talert(seq + \"번 투표 기간변경 이동!!!\");\r\n");
      out.write("            \t\tvar sday = $('#sd' + seq).text().replace(/\\./g, '-');\r\n");
      out.write("            \t\tvar eday = $('#ed' + seq).text().replace(/\\./g, '-');\r\n");
      out.write("            \t\talert(\"시작일 : \" + sday + \"    종료일 : \" + eday);\r\n");
      out.write("            \t\t$('#pollModifyModal').on('show.bs.modal', function(event) {\r\n");
      out.write("            \t\t\tvar modal = $(this)\r\n");
      out.write("              \t\t  \tmodal.find('#startDay').val('20' + sday);\r\n");
      out.write("                \t\tmodal.find('#endDay').val('20' + eday);\r\n");
      out.write("                \t\tmodal.find('#charttype').val('p');\r\n");
      out.write("                \t\tmodal.find('#question').val('질문이 나와요!!!!');\r\n");
      out.write("                \t\tfor(var i=1;i<5;i++) {\r\n");
      out.write("                \t\t\tvar lab = $('<label class=\"col-sm-3\"></label>');\r\n");
      out.write("\t                \t\tvar inp = $('<div class=\"col-sm-8\">')\r\n");
      out.write("\t                \t\t\t\t\t.append('<input type=\"text\" name=\"answer\" class=\"answerInp form-control\" value=\"답변문항' + i + '입니다.\" readonly=\"readonly\">');\r\n");
      out.write("\t                \t\tmodal.find('#answerDivM').append(lab).append(inp);\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("              \t\t});          \t\r\n");
      out.write("              \t\t$('#pollModifyModal').modal();\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t//투표종료\r\n");
      out.write("            \t$('.btn.btn-xs.btn-danger').click(function() {\r\n");
      out.write("            \t\tvar seq = $(this).parents('td').siblings().eq(0).text();\r\n");
      out.write("            \t\talert(seq + \"번 투표 종료!!!\");\r\n");
      out.write("            \t});\r\n");
      out.write("            \t\r\n");
      out.write("            });\r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write(" \t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("            \t\t<table class=\"table table-hover\">\r\n");
      out.write("                    \t<colgroup>\r\n");
      out.write("                        <col width=\"80\">\r\n");
      out.write("                        <col width=\"*\">\r\n");
      out.write("                        <col width=\"80\">\r\n");
      out.write("                        <col width=\"220\">\r\n");
      out.write("                        <col width=\"220\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr><th colspan=\"5\"></th></tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"text-center\">번호</th>\r\n");
      out.write("                        <th class=\"text-center\">질문</th>\r\n");
      out.write("                        <th class=\"text-center\">참여수</th>\r\n");
      out.write("                        <th class=\"text-center\">투표기간</th>\r\n");
      out.write("                        <th class=\"text-center\">비고</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody class=\"notice_list\">\r\n");
      out.write("                        <!--<tr><td colspan=\"5\" class=\"text-center\">가입한 회원이 없습니다.</td></tr>-->\r\n");
      out.write("                        <tr data-seq=\"2\">\r\n");
      out.write("                            <td class=\"text-center\">2</td>\r\n");
      out.write("                            <td class=\"subject\">이번 여름 휴가지로 가고싶은곳은?</td>\r\n");
      out.write("                            <td class=\"text-center\">3258</td>\r\n");
      out.write("                            <td class=\"text-center\"><span id=\"sd2\">17.07.01</span> ~ <span id=\"ed2\">17.07.30</span></td>\r\n");
      out.write("                            <td class=\"etc text-center\">\r\n");
      out.write("                            \t<button type=\"button\" id=\"pollResultBtn\" class=\"btn btn-xs btn-primary\" data-backdrop=\"static\">결과보기</button>\r\n");
      out.write("            \t\t\t\t\t<button type=\"button\" id=\"pollModifyBtn\" class=\"btn btn-xs btn-info\" data-backdrop=\"static\">기간변경</button>\r\n");
      out.write("            \t\t\t\t\t<button type=\"button\" id=\"pollStopBtn\" class=\"btn btn-xs btn-danger\" data-backdrop=\"static\">투표종료</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr data-seq=\"1\">\r\n");
      out.write("                            <td class=\"text-center\">1</td>\r\n");
      out.write("                            <td class=\"subject\">가장 좋아하는 과목은 무엇입니까??</td>\r\n");
      out.write("                            <td class=\"text-center\">1867</td>\r\n");
      out.write("                            <td class=\"text-center\"><span id=\"sd1\">17.06.01</span> ~ <span id=\"ed1\">17.06.15</span></td>\r\n");
      out.write("                            <td class=\"etc text-center\">\r\n");
      out.write("                            \t<button type=\"button\" id=\"pollResultBtn\" class=\"btn btn-xs btn-primary\" data-backdrop=\"static\">결과보기</button>\r\n");
      out.write("            \t\t\t\t\t<button type=\"button\" id=\"pollModifyBtn\" class=\"btn btn-xs btn-info\" data-backdrop=\"static\">기간변경</button>\r\n");
      out.write("            \t\t\t\t\t<button type=\"button\" id=\"pollStopBtn\" class=\"btn btn-xs btn-danger\" data-backdrop=\"static\">투표종료</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-12\" style=\"height: 5px;\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-12\">\r\n");
      out.write("\t        <form class=\"form-search\">\r\n");
      out.write("\t            <div class=\"input-group\">\r\n");
      out.write("\t                <input type=\"text\" class=\"form-control\" placeholder=\"제목\">\r\n");
      out.write("\t                <span class=\"input-group-btn\">\r\n");
      out.write("\t                    <button type=\"submit\" class=\"btn btn-primary\">검색</button>\r\n");
      out.write("\t                </span>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"col-sm-12\" style=\"text-align: center;\">\r\n");
      out.write("          \t<ul class=\"pagination\">\r\n");
      out.write("          \t\t<li class=\"firstpage\">\r\n");
      out.write("          \t\t\t<a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("          \t\t\t\t<span aria-hidden=\"true\">최신</span>\r\n");
      out.write("          \t\t\t</a>\r\n");
      out.write("\t\t    \t</li>\r\n");
      out.write("          \t\t<li class=\"page\" data-page=\"0\">\r\n");
      out.write("          \t\t\t<a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("          \t\t\t\t<span aria-hidden=\"true\">이전</span>\r\n");
      out.write("          \t\t\t</a>\r\n");
      out.write("\t\t\t    </li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"1\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page active\" data-page=\"2\"><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"3\"><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"4\"><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"5\"><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"6\"><a href=\"#\">6</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"7\"><a href=\"#\">7</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"8\"><a href=\"#\">8</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"9\"><a href=\"#\">9</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"10\"><a href=\"#\">10</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"page\" data-page=\"11\">\r\n");
      out.write("\t          \t\t<a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t          \t\t\t<span aria-hidden=\"true\">다음</span>\r\n");
      out.write("\t          \t\t</a>\r\n");
      out.write("\t\t\t    </li>\r\n");
      out.write("\t\t\t    <li class=\"page\" data-page=\"100\">\r\n");
      out.write("\t          \t\t<a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t          \t\t\t<span aria-hidden=\"true\">마지막</span>\r\n");
      out.write("\t          \t\t</a>\r\n");
      out.write("\t\t\t    </li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("       \t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 공지사항 작성 Modal -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar answerCount = 1;\r\n");
      out.write("\t$('#answerPlusBtn').click(function() {\r\n");
      out.write("\t\tvar inp = $('<div class=\"col-sm-11\">').append('<input type=\"text\" name=\"answer\" class=\"answerInp form-control\" placeholder=\"문항\">');\r\n");
      out.write("\t\tvar btn = $('<div class=\"col-sm-1\">').append('<button type=\"button\" class=\"answerMinusBtn btn btn-md btn-warning\">문항제거</button>');\r\n");
      out.write("\t\t$('<div id=\"answerD\" class=\"col-sm-10\">').append(inp).append(btn).appendTo('#answerDiv');\r\n");
      out.write("\t\tanswerCount++;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click', '.answerMinusBtn', function() {\r\n");
      out.write("\t\t//$(this).parents('#answerD').css('border', '2px solid blue');\r\n");
      out.write("\t\t$(this).parents('#answerD').remove();\r\n");
      out.write("\t\tanswerCount--;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click', '#writeBtn', function() {\r\n");
      out.write("\t\t//http://naradesign.net/wp/2011/07/20/1663/ << 유효성검사\r\n");
      out.write("\t\talert(\">>>> \" + $('.answerInp').length);\r\n");
      out.write("\t\tif($('#startDay').val() > $('#endDay').val()) {\r\n");
      out.write("\t\t\talert(\"투표기간 오류!!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else if(answerCount < 2) {\r\n");
      out.write("\t\t\talert(\"설문 문항 오류!!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"투표생성!!!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"pollWriteModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"width: 50%;\">\r\n");
      out.write("\t    <!-- Modal content-->\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t        \t<h4 class=\"modal-title\">투표생성</h4>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t    <form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t    \t<fieldset>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">투표기간</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                        <input type=\"date\" id=\"startDay\" class=\"form-control\" placeholder=\"시작일\">\r\n");
      out.write("\t                        <input type=\"date\" id=\"endDay\" class=\"form-control\" placeholder=\"종료일\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">그래프형식</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                        <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t\t\t<select id=\"charttype\" class=\"form-control\">\r\n");
      out.write("\t\t                        \t<option value=\"line\">line\r\n");
      out.write("\t\t                        \t<option value=\"bar\">bar\r\n");
      out.write("\t\t                        \t<option value=\"horizontalBar\">horizontalBar\r\n");
      out.write("\t\t                        \t<option value=\"pie\">pie\r\n");
      out.write("\t\t                        \t<option value=\"doughnut\">doughnut\r\n");
      out.write("\t\t                        \t<option value=\"polarArea\">polarArea\r\n");
      out.write("\t\t                        \t<option value=\"bubble\">bubble\r\n");
      out.write("\t\t                        \t<option value=\"radar\">radar\r\n");
      out.write("\t\t                        </select>\r\n");
      out.write("\t\t\t\t    \t\t</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">주제</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"question\" class=\"form-control\" placeholder=\"주제\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">문항</label>\r\n");
      out.write("\t\t\t\t    \t\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                    \t<button type=\"button\" id=\"answerPlusBtn\" class=\"btn btn-md btn-warning\">문항추가</button>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div id=\"answerDiv\" class=\"form-group\">\r\n");
      out.write("                    \t<div id=\"answerD\" class=\"col-sm-10\">\r\n");
      out.write("\t                    \t<div class=\"col-sm-11\">\r\n");
      out.write("\t                        \t<input type=\"text\" name=\"answer\" class=\"answerInp form-control\" placeholder=\"문항\">\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"answerMinusBtn btn btn-md btn-warning\">문항제거</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t      \t\t<button type=\"button\" id=\"writeBtn\" class=\"btn btn-info\">투표생성</button>\r\n");
      out.write("\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 공지사항 보기 Modal -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"pollResultModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"width: 80%;\">\r\n");
      out.write("\t    <!-- Modal content-->\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t        \t<h4 class=\"modal-title\">투표결과</h4>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"modal-body\">\r\n");
      out.write("\t\t    \t<div class=\"row\">\r\n");
      out.write("\t\t    \t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\">질문</label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"subject\" class=\"col-sm-12 control-label\">질문이 나올거에요</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t\t\t        <div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\">설문기간</label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"content\" class=\"col-sm-12 control-label\">2017.07.01 ~ 2017.07.30</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\">응답수</label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"content\" class=\"col-sm-12 control-label\">5214명</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <!-- 여기부터 for문돌려라 -->\r\n");
      out.write("\t\t                <div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\">문항별 선택</label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"content\" class=\"col-sm-12 control-label\">Red : 300</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\"></label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"content\" class=\"col-sm-12 control-label\">Blue : 50</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\"></label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"content\" class=\"col-sm-12 control-label\">Yellow : 100</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"col-sm-12\" style=\"margin: 10px;\">\r\n");
      out.write("\t\t\t\t\t    \t<label class=\"col-sm-3 control-label\"></label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t                        <label id=\"content\" class=\"col-sm-12 control-label\">Green : 160</label>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <!-- 여기까지 for문돌려라 -->\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t\t\t<select id=\"charttype1\" class=\"form-control\">\r\n");
      out.write("\t\t                        \t<option value=\"line\">line\r\n");
      out.write("\t\t                        \t<option value=\"bar\">bar\r\n");
      out.write("\t\t                        \t<option value=\"horizontalBar\">horizontalBar\r\n");
      out.write("\t\t                        \t<option value=\"pie\">pie\r\n");
      out.write("\t\t                        \t<option value=\"doughnut\">doughnut\r\n");
      out.write("\t\t                        \t<option value=\"polarArea\">polarArea\r\n");
      out.write("\t\t                        \t<option value=\"bubble\">bubble\r\n");
      out.write("\t\t                        \t<option value=\"radar\">radar\r\n");
      out.write("\t\t                        </select>\r\n");
      out.write("\t\t\t\t    \t\t</div>\r\n");
      out.write("\t                        <canvas id=\"pollChart1\"></canvas>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("<!--  \r\n");
      out.write("\t                    <div class=\"col-sm-6\">\r\n");
      out.write("\t                    \t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t    \t\t\t<select id=\"charttype2\" class=\"form-control\">\r\n");
      out.write("\t\t                        \t<option value=\"line\">line\r\n");
      out.write("\t\t                        \t<option value=\"bar\">bar\r\n");
      out.write("\t\t                        \t<option value=\"horizontalBar\">horizontalBar\r\n");
      out.write("\t\t                        \t<option value=\"pie\">pie\r\n");
      out.write("\t\t                        \t<option value=\"doughnut\">doughnut\r\n");
      out.write("\t\t                        \t<option value=\"polarArea\">polarArea\r\n");
      out.write("\t\t                        \t<option value=\"bubble\">bubble\r\n");
      out.write("\t\t                        \t<option value=\"radar\">radar\r\n");
      out.write("\t\t                        </select>\r\n");
      out.write("\t\t\t\t    \t\t</div>\r\n");
      out.write("\t                        <canvas id=\"pollChart2\"></canvas>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("-->\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$('#charttype1').change(function() {\r\n");
      out.write("\tmakeChart('pollChart1', 'charttype1');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#charttype2').change(function() {\r\n");
      out.write("\tmakeChart('pollChart2', 'charttype2');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function makeChart(can, ct) {\r\n");
      out.write("\tclearCanvas(can);\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(pollChart);\r\n");
      out.write("\t//pollChart.destroy();\r\n");
      out.write("\t\r\n");
      out.write("\t//var ctx = $(can);\r\n");
      out.write("\tvar pollChart = new Chart($('#'+can), {\r\n");
      out.write("\t\ttype: $('#'+ct).val(),\r\n");
      out.write("\t\tdata: {\r\n");
      out.write("\t    \tlabels: [\"Red\",\r\n");
      out.write("\t              \t\"Blue\",\r\n");
      out.write("\t              \t\"Yellow\",\r\n");
      out.write("\t              \t\"Green\"],\r\n");
      out.write("\t    \tdatasets: [{\r\n");
      out.write("\t        \tlabel: '# of Votes',\r\n");
      out.write("\t        \tdata: [300, 150, 100, 160],\r\n");
      out.write("\t        \tbackgroundColor: [\r\n");
      out.write("\t            \t'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("\t            \t'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("\t            \t'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("\t            \t'rgba(5, 255, 24, 0.2)'\r\n");
      out.write("\t        \t],\r\n");
      out.write("\t        \tborderColor: [\r\n");
      out.write("\t            \t'rgba(255,99,132,1)',\r\n");
      out.write("\t            \t'rgba(54, 162, 235, 1)',\r\n");
      out.write("\t            \t'rgba(255, 206, 86, 1)',\r\n");
      out.write("\t            \t'rgba(5, 255, 24, 0.2)'\r\n");
      out.write("\t        \t],\r\n");
      out.write("\t    \t}]\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\toptions: {\r\n");
      out.write("\t\t\t/*scales: {\r\n");
      out.write("\t\t\t\tyAxes: [{\r\n");
      out.write("\t\t\t\t\tticks: {\r\n");
      out.write("\t\t\t\t\t\tbeginAtZero:true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t}*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function clearCanvas(can){\r\n");
      out.write("\t//alert(can);\r\n");
      out.write("\t//$('#' + can).css('border', '3px solid red');\r\n");
      out.write("\t//$('#' + can).parent('div').css('border', '3px solid blue');\r\n");
      out.write("\tvar canparent = $('#' + can).parent();\r\n");
      out.write("    $('#' + can).remove(); \r\n");
      out.write("    canparent.append('<canvas id=\"' + can + '\"></canvas>');\r\n");
      out.write("}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 공지사항 수정 Modal -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$(document).on('click', '#modifyBtn', function() {\r\n");
      out.write("\t\tif($('#startDay').val() > $('#endDay').val()) {\r\n");
      out.write("\t\t\talert(\"투표기간 오류!!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"투표수정!!!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"pollModifyModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"width: 50%;\">\r\n");
      out.write("\t    <!-- Modal content-->\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t    \t<div class=\"modal-header\">\r\n");
      out.write("\t        \t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t        \t<h4 class=\"modal-title\">투표수정</h4>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t    <form class=\"form-horizontal\" action=\"#\">\r\n");
      out.write("\t\t\t    \t<fieldset>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">투표기간</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                        <input type=\"date\" id=\"startDay\" class=\"form-control\" placeholder=\"시작일\">\r\n");
      out.write("\t                        <input type=\"date\" id=\"endDay\" class=\"form-control\" placeholder=\"종료일\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">그래프형식</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                        <select id=\"charttype\" class=\"form-control\">\r\n");
      out.write("\t                        \t<option value=\"b\">바차트\r\n");
      out.write("\t                        \t<option value=\"p\">파이차트\r\n");
      out.write("\t                        \t<option value=\"g\">꺽은선차트\r\n");
      out.write("\t                        \t<option value=\"l\">라인차트\r\n");
      out.write("\t                        \t<option value=\"b\">버블차트\r\n");
      out.write("\t                        </select>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">주제</label>\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"col-sm-8\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"question\" class=\"form-control\" placeholder=\"주제\" readonly=\"readonly\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t<label class=\"col-sm-3 control-label\">문항</label>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div id=\"answerDivM\" class=\"form-group\"></div>\r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t      \t<div class=\"modal-footer\">\r\n");
      out.write("\t      \t\t<button type=\"button\" id=\"modifyBtn\" class=\"btn btn-info\">투표수정</button>\r\n");
      out.write("\t        \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /common/public.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /common/public.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/common/public.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
