CREATE TABLE DEMEMP
AS
  SELECT * FROM EMP WHERE 1 = 2;
  
ALTER TABLE DEMEMP
ADD CONSTRAINT PK_DEMEMP_EMPNO PRIMARY KEY(EMPNO);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEMEMP';

SELECT * FROM DEMEMP;

INSERT INTO DEMEMP
SELECT * FROM EMP;

COMMIT;

SELECT * FROM DEMEMP
ORDER BY DEPTNO;

SELECT * FROM DEMEMP;